- hosts: neosavvy

  tasks:
    - name: install nginx
      action: apt pkg=nginx state=absent
    - name: disable the neosavvy proxy from available
      file: dest=/etc/nginx/sites-available/neosavvy-proxy state=absent
    - name: disable the proxy from enabled
      file: dest=/etc/nginx/sites-enabled/neosavvy-proxy state=absent
#http://www.ansibleworks.com/docs/modules.html#copy
