- hosts: runenergy

  tasks:
    - name: install tar
      get_url: url=http://nodejs.org/dist/v0.10.23/node-v0.10.23-linux-x64.tar.gz dest=/tmp/node.tar.gz

    - name: install python software properties
      apt: pkg=python-software-properties state=present

    - name: add chris lea node repo
      apt_repository: repo='ppa:chris-lea/node.js'

    - name: install node
      apt: pkg=nodejs state=present update_cache=yes

    - name: install fontconfig
      apt: pkg=fontconfig state=present

    - name: add grunt-cli
      npm: name=grunt-cli global=yes

    - name: add karma
      npm: name=karma global=yes

    - name: add phantom js
      npm: name=phantomjs global=yes
